# Generated by Django 5.2.7 on 2025-12-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_camera_cash_confidence_camera_cashier_zone_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('online', '활성'), ('offline', '오프라인'), ('maintenance', '점검중')], default='online', max_length=20),
        ),
    ]
