# Generated by Django 5.2.7 on 2025-12-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_add_hand_touch_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='pose_confidence',
            field=models.FloatField(default=0.3),
        ),
    ]
