# Generated by Django 5.2.7 on 2025-12-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerState',
        ),
    ]
