# Generated by Django 5.2.7 on 2025-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cash_confidence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='camera',
            name='cashier_zone_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='custom_fire_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='custom_pose_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='custom_yolo_model',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='fire_confidence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='camera',
            name='violence_confidence',
            field=models.FloatField(default=0.6),
        ),
        migrations.AlterField(
            model_name='camera',
            name='cashier_zone_height',
            field=models.IntegerField(default=480),
        ),
        migrations.AlterField(
            model_name='camera',
            name='cashier_zone_width',
            field=models.IntegerField(default=640),
        ),
        migrations.AlterField(
            model_name='camera',
            name='cashier_zone_y',
            field=models.IntegerField(default=0),
        ),
    ]
