# Generated by Django 5.2.7 on 2025-12-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_delete_workerstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cash_drawer_zone_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='camera',
            name='cash_drawer_zone_height',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='camera',
            name='cash_drawer_zone_width',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='camera',
            name='cash_drawer_zone_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='cash_drawer_zone_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='hand_tracking_duration',
            field=models.IntegerField(default=90),
        ),
    ]
