# Generated by Django 6.0 on 2025-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_polygon_zones_gemini_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('cash', '현금'), ('potential_cash', '잠재 현금'), ('fire', '화재'), ('violence', '난동')], max_length=20),
        ),
    ]
