# Generated by Django 6.0 on 2025-12-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='show_pose_overlay',
            field=models.BooleanField(default=False, help_text='Enable developer mode logging in detector'),
        ),
    ]
