# Generated by Django 5.2.7 on 2025-12-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_add_pose_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='metadata',
            field=models.TextField(blank=True, help_text='JSON with detection parameters', null=True),
        ),
    ]
