# Generated by Django 5.2.7 on 2025-12-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0006_add_event_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.IntegerField(db_index=True, unique=True)),
                ('camera_code', models.CharField(max_length=50)),
                ('running', models.BooleanField(default=False)),
                ('status', models.CharField(default='stopped', max_length=20)),
                ('process_id', models.IntegerField(null=True)),
                ('thread_id', models.CharField(max_length=50, null=True)),
                ('frame_count', models.IntegerField(default=0)),
                ('events_detected', models.IntegerField(default=0)),
                ('frames_processed', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'worker_states',
                'ordering': ['camera_id'],
            },
        ),
    ]
