# Generated by Django 6.0 on 2025-12-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0006_camera_show_pose_overlay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='gemini_cash_prompt',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='gemini_fire_prompt',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='gemini_violence_prompt',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='show_pose_overlay',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='use_polygon_zones',
        ),
    ]
