# Generated by Django 6.0 on 2025-12-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0007_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='cash_drawer_zone_height',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='cash_drawer_zone_width',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='cash_drawer_zone_x',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='cash_drawer_zone_y',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='cashier_zone_height',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='cashier_zone_width',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='cashier_zone_x',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='cashier_zone_y',
        ),
    ]
