# Generated by Django 6.0 on 2025-12-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0008_remove_rectangle_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unified_prompt', models.TextField(blank=True, help_text='Unified prompt for all detection types (cash, violence, fire)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gemini AI Prompt',
                'verbose_name_plural': 'Gemini AI Prompts',
                'db_table': 'gemini_prompts',
            },
        ),
    ]
