# Generated by Django 5.2.6 on 2026-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cctv", "0010_add_gemini_validation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="pms_project_id",
            field=models.CharField(
                blank=True,
                help_text="UUID from PMS project for synchronization",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="pms_project_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
