# Generated by Django 5.2.6 on 2026-01-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cctv", "0011_add_pms_project_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="cctv.region",
            ),
        ),
    ]
